base_measure_params:
  alpha: 1
  beta: 1
beta_binomial_precision_params:
  prior:
    rate: 0.001
    shape: 1.0
  proposal:
    precision: 0.01
  value: 1000
concentration:
  prior:
    rate: 0.001
    shape: 1.0
  value: 1.0
density: pyclone_beta_binomial
num_iters: 10000
samples:
  BM35_M:
    error_rate: 0.001
    mutations_file: /lustre/rde/user/guoxc/project/181126_12Sample_BrM/phylogenetic/INcloudL/05Pyclone/BM35/yaml/BM35_M.yaml
    tumour_content:
      value: 1.0
  BM35_P:
    error_rate: 0.001
    mutations_file: /lustre/rde/user/guoxc/project/181126_12Sample_BrM/phylogenetic/INcloudL/05Pyclone/BM35/yaml/BM35_P.yaml
    tumour_content:
      value: 1.0
trace_dir: trace
working_dir: /lustre/rde/user/guoxc/project/181126_12Sample_BrM/phylogenetic/INcloudL/05Pyclone/BM35
